name: Renovate

on:
  schedule:
    # 9:05 AM GMT-3 = 12:05 PM UTC
    - cron: "5 12 * * 3"
  workflow_dispatch:
    inputs:
      debug:
        description: "Run Renovate with DEBUG log level"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      debug:
        description: "Run Renovate with DEBUG log level"
        required: false
        default: false
        type: boolean
      config_file:
        description: "Path to Renovate configuration file"
        required: false
        default: ".github/renovate.json"
        type: string
    secrets:
      RENOVATE_TOKEN:
        description: "GitHub token for Renovate"
        required: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8cb0d4a6ab7d8bb90460a005f7bd33b80dd07ca8 # v44.2.5
        env:
          LOG_LEVEL: ${{ inputs.debug && 'debug' || 'info' }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: ${{ inputs.config_file || '.github/renovate.json' }}
          token: ${{ secrets.RENOVATE_TOKEN }}
