name: Renovate

on:
  workflow_call:
    inputs:
      debug:
        description: "Run Renovate with DEBUG log level"
        required: false
        default: false
        type: boolean
      config_file:
        description: "Path to Renovate configuration file"
        required: false
        default: ".github/renovate.json"
        type: string
    secrets:
      RENOVATE_TOKEN:
        description: "GitHub token for Renovate"
        required: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e084a0022424929b89d0d9af459c46c5a3f97f24 # v45.4.0
        env:
          LOG_LEVEL: ${{ inputs.debug && 'debug' || 'info' }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: ${{ inputs.config_file }}
          token: ${{ secrets.RENOVATE_TOKEN }}
